default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: 35.185.128.127
  # host: 104.199.252.193 
  port: 3306

development:
  <<: *default
  database: fc2

test:
  <<: *default
  database: fc2

production:
  <<: *default
  database: fc2